#!/bin/bash
#
#varunda_db_kasutaja
#
echo -n "Kasutajanimi: "
read KASUTAJA
DB1=$(mysql -e "SHOW DATABASES;" | grep "$KASUTAJA"_*)

mysqldump $DB1 | bzip2 -c > $(date +%Y-%m-%d-%H.%M.)$DB1.backup.sql.bz2
mv $(date +%Y-%m-%d-%H.%M.)$DB1.backup.sql.bz2 /mysql_backup
