#!/bin/bash
#
#masina_ip/~kasutajanimi/public/avalik_dokument
#
echo -n "Sisestage kasutajanimi: "
read KASUTAJA
if [ ! -f /etc/apache2/mods-enabled/userdir.conf ]; then
	a2enmod userdir
	service apache2 restart
fi
perl -pi -e "s/public_html/public/g" /etc/apache2/mods-enabled/userdir.conf

if [ ! -d /home/$KASUTAJA/public ]; then
	mkdir /home/$KASUTAJA/public
	chmod 777 /home/$KASUTAJA/public
fi

#Kuna mul on nginx paigaltatud on vaja ka nginxi configi muuta

cat /etc/nginx/sites-enabled/default | grep "location ~ ^/~(.+?)(/.*)?$ {" > /dev/null

if [ `echo $?` -eq 1 ]; then
	sudo echo 'location ~ ^/~(.+?)(/.*)?$ {' >> /etc/nginx/sites-enabled/default
	sudo echo 'alias /home/$1/public$2;' >> /etc/nginx/sites-enabled/default
	sudo echo 'index  index.html index.htm;' >> /etc/nginx/sites-enabled/default
	sudo echo 'autoindex on;' >> /etc/nginx/sites-enabled/default
	sudo echo '}' >> /etc/nginx/sites-enabled/default
fi
